# -*- coding: utf-8 -*-
"""DataPreProcessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iKfrE4WArlkpHOJmVrVuGR8vjg4fZ5Hr
"""

import os.path
import pickle
import numpy as np
import torch
from torch.utils.data import TensorDataset, DataLoader
import cv2
import random
from datapreprocessing import *
import sys  
sys.path.insert(0, '../')

t_a, t_v, t_y = load_processed_data('train') 
v_a, v_v, v_y = load_processed_data('val') 
test_a, test_v, test_y = load_processed_data('test') 
data_sets = {
    "train": AudioVisualDataset(t_a, t_v, t_y),
    "val": AudioVisualDataset(v_a, v_v, v_y),
    "test": AudioVisualDataset(test_a, test_v, test_y),
}

print("Making dataloaders")
data_loaders = {data_key:
                DataLoader(data_val,
                           batch_size=30,
                           shuffle=True, 
                           num_workers=4) 
                for data_key, data_val in data_sets.items()
                }
print("Saving dataloaders")             
torch.save(data_loaders, datapath + 'audiovisual_dataloader.pkl')
